/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include "AS3/AS3.h"
#define swig_as3(X) inline_as3("import com.adobe.flascc.swig.*; " X)


/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) {int msglen = strlen(msg);__asm__ volatile ("throw new Exception(CModule.readString(%0, %1))": : "r"(msg), "r"(msglen));}



#include <stdlib.h>
#include <vector>
#include "source/ODGame.h"
#include "source/ODGameData.h"

__attribute__((annotate("as3sig:public function _wrap_Scene_Instance():int")))
void _wrap_Scene_Instance() {
  Scene *result ;
  
  result = (Scene *)Scene::Instance();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Scene_Reset(self):void")))
void _wrap_Scene_Reset() {
  Scene *arg1 = (Scene *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  (arg1)->Reset();
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Scene_getWidth(self):Number")))
void _wrap_Scene_getWidth() {
  Scene *arg1 = (Scene *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float)(arg1)->getWidth();
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Scene_getHeight(self):Number")))
void _wrap_Scene_getHeight() {
  Scene *arg1 = (Scene *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float)(arg1)->getHeight();
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Scene_getBorderWidth(self):Number")))
void _wrap_Scene_getBorderWidth() {
  Scene *arg1 = (Scene *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float)(arg1)->getBorderWidth();
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Scene_getBorderHeight(self):Number")))
void _wrap_Scene_getBorderHeight() {
  Scene *arg1 = (Scene *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float)(arg1)->getBorderHeight();
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_delete_Scene(self):void")))
void _wrap_delete_Scene() {
  Scene *arg1 = (Scene *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  delete arg1;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ENpcTypeWest():int")))
void _wrap_ENpcTypeWest() {
  int result ;
  
  result = ENpcTypeWest;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ENpcTypeNorth():int")))
void _wrap_ENpcTypeNorth() {
  int result ;
  
  result = ENpcTypeNorth;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ENpcTypeEast():int")))
void _wrap_ENpcTypeEast() {
  int result ;
  
  result = ENpcTypeEast;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ENpcTypeSouth():int")))
void _wrap_ENpcTypeSouth() {
  int result ;
  
  result = ENpcTypeSouth;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ENpcTypeMax():int")))
void _wrap_ENpcTypeMax() {
  int result ;
  
  result = ENpcTypeMax;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_new_Bullet():int")))
void _wrap_new_Bullet() {
  Bullet *result ;
  
  result = (Bullet *)new Bullet();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Bullet_Init(self, srcx:Number, srcy:Number, dstx:Number, dsty:Number):void")))
void _wrap_Bullet_Init() {
  Bullet *arg1 = (Bullet *) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  float arg5 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, srcx);
  }
  {
    AS3_GetScalarFromVar(arg3, srcy);
  }
  {
    AS3_GetScalarFromVar(arg4, dstx);
  }
  {
    AS3_GetScalarFromVar(arg5, dsty);
  }
  (arg1)->Init(arg2,arg3,arg4,arg5);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Bullet_Update(self, deltaTime:Number):void")))
void _wrap_Bullet_Update() {
  Bullet *arg1 = (Bullet *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, deltaTime);
  }
  (arg1)->Update(arg2);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Bullet_CheckOutofScene(self):Boolean")))
void _wrap_Bullet_CheckOutofScene() {
  Bullet *arg1 = (Bullet *) 0 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (bool)(arg1)->CheckOutofScene();
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Bullet_getPosX(self):Number")))
void _wrap_Bullet_getPosX() {
  Bullet *arg1 = (Bullet *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float)(arg1)->getPosX();
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Bullet_getPosY(self):Number")))
void _wrap_Bullet_getPosY() {
  Bullet *arg1 = (Bullet *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float)(arg1)->getPosY();
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Bullet_CheckIsHitPlayer(self, x:Number, y:Number, r:Number):Boolean")))
void _wrap_Bullet_CheckIsHitPlayer() {
  Bullet *arg1 = (Bullet *) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, x);
  }
  {
    AS3_GetScalarFromVar(arg3, y);
  }
  {
    AS3_GetScalarFromVar(arg4, r);
  }
  result = (bool)(arg1)->CheckIsHitPlayer(arg2,arg3,arg4);
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Bullet_CheckIsHitNpc(self, x:Number, y:Number, r:Number, e:int):Boolean")))
void _wrap_Bullet_CheckIsHitNpc() {
  Bullet *arg1 = (Bullet *) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  eNpcType arg5 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, x);
  }
  {
    AS3_GetScalarFromVar(arg3, y);
  }
  {
    AS3_GetScalarFromVar(arg4, r);
  }
  {
    AS3_GetScalarFromVar(arg5, e);
  }
  result = (bool)(arg1)->CheckIsHitNpc(arg2,arg3,arg4,arg5);
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Bullet_setFromNpcType(self, e:int):void")))
void _wrap_Bullet_setFromNpcType() {
  Bullet *arg1 = (Bullet *) 0 ;
  eNpcType arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, e);
  }
  (arg1)->setFromNpcType(arg2);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_delete_Bullet(self):void")))
void _wrap_delete_Bullet() {
  Bullet *arg1 = (Bullet *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  delete arg1;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletManager_Instance():int")))
void _wrap_BulletManager_Instance() {
  BulletManager *result ;
  
  result = (BulletManager *)BulletManager::Instance();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletManager_Update(self, deltaTime:Number):void")))
void _wrap_BulletManager_Update() {
  BulletManager *arg1 = (BulletManager *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, deltaTime);
  }
  (arg1)->Update(arg2);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletManager_spawnBullet(self, srcX:Number, srcY:Number, dstX:Number, dstY:Number, e:int):void")))
void _wrap_BulletManager_spawnBullet() {
  BulletManager *arg1 = (BulletManager *) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  float arg5 ;
  eNpcType arg6 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, srcX);
  }
  {
    AS3_GetScalarFromVar(arg3, srcY);
  }
  {
    AS3_GetScalarFromVar(arg4, dstX);
  }
  {
    AS3_GetScalarFromVar(arg5, dstY);
  }
  {
    AS3_GetScalarFromVar(arg6, e);
  }
  (arg1)->spawnBullet(arg2,arg3,arg4,arg5,arg6);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletManager_getBullets(self):int")))
void _wrap_BulletManager_getBullets() {
  BulletManager *arg1 = (BulletManager *) 0 ;
  std::vector< Bullet > *result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (std::vector< Bullet > *)(arg1)->getBullets();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletManager_CheckIsHitPlayer(self, posX:Number, posY:Number, radius:Number):Boolean")))
void _wrap_BulletManager_CheckIsHitPlayer() {
  BulletManager *arg1 = (BulletManager *) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, posX);
  }
  {
    AS3_GetScalarFromVar(arg3, posY);
  }
  {
    AS3_GetScalarFromVar(arg4, radius);
  }
  result = (bool)(arg1)->CheckIsHitPlayer(arg2,arg3,arg4);
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletManager_CheckIsHitNpc(self, posX:Number, posY:Number, radius:Number, e:int):Boolean")))
void _wrap_BulletManager_CheckIsHitNpc() {
  BulletManager *arg1 = (BulletManager *) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  eNpcType arg5 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, posX);
  }
  {
    AS3_GetScalarFromVar(arg3, posY);
  }
  {
    AS3_GetScalarFromVar(arg4, radius);
  }
  {
    AS3_GetScalarFromVar(arg5, e);
  }
  result = (bool)(arg1)->CheckIsHitNpc(arg2,arg3,arg4,arg5);
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletManager_Reset(self):Boolean")))
void _wrap_BulletManager_Reset() {
  BulletManager *arg1 = (BulletManager *) 0 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (bool)(arg1)->Reset();
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_delete_BulletManager(self):void")))
void _wrap_delete_BulletManager() {
  BulletManager *arg1 = (BulletManager *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  delete arg1;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_EMoveLeft():int")))
void _wrap_EMoveLeft() {
  int result ;
  
  result = EMoveLeft;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_EMoveRight():int")))
void _wrap_EMoveRight() {
  int result ;
  
  result = EMoveRight;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_EMoveUp():int")))
void _wrap_EMoveUp() {
  int result ;
  
  result = EMoveUp;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_EMoveDown():int")))
void _wrap_EMoveDown() {
  int result ;
  
  result = EMoveDown;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_EMaxCommand():int")))
void _wrap_EMaxCommand() {
  int result ;
  
  result = EMaxCommand;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Player_commands_set(self, commands:int):void")))
void _wrap_Player_commands_set() {
  Player *arg1 = (Player *) 0 ;
  bool *arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, commands);
  }
  {
    size_t ii;
    bool *b = (bool *) arg1->commands;
    for (ii = 0; ii < (size_t)EMaxCommand; ii++) b[ii] = *((bool *) arg2 + ii);
  }
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Player_commands_get(self):int")))
void _wrap_Player_commands_get() {
  Player *arg1 = (Player *) 0 ;
  bool *result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (bool *)(bool *) ((arg1)->commands);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_new_Player():int")))
void _wrap_new_Player() {
  Player *result ;
  
  result = (Player *)new Player();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Player_Reset(self):void")))
void _wrap_Player_Reset() {
  Player *arg1 = (Player *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  (arg1)->Reset();
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Player_Update(self, deltaTime:Number):void")))
void _wrap_Player_Update() {
  Player *arg1 = (Player *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, deltaTime);
  }
  (arg1)->Update(arg2);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Player_getPosX(self):Number")))
void _wrap_Player_getPosX() {
  Player *arg1 = (Player *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float)(arg1)->getPosX();
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Player_getPosY(self):Number")))
void _wrap_Player_getPosY() {
  Player *arg1 = (Player *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float)(arg1)->getPosY();
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Player_getRadius(self):Number")))
void _wrap_Player_getRadius() {
  Player *arg1 = (Player *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float)(arg1)->getRadius();
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Player_getAlive(self):Boolean")))
void _wrap_Player_getAlive() {
  Player *arg1 = (Player *) 0 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (bool)(arg1)->getAlive();
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Player_getScore(self):int")))
void _wrap_Player_getScore() {
  Player *arg1 = (Player *) 0 ;
  int result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (int)(arg1)->getScore();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Player_setScore(self, _score:int):void")))
void _wrap_Player_setScore() {
  Player *arg1 = (Player *) 0 ;
  int arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, _score);
  }
  (arg1)->setScore(arg2);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_delete_Player(self):void")))
void _wrap_delete_Player() {
  Player *arg1 = (Player *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  delete arg1;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_new_Npc(_type:int):int")))
void _wrap_new_Npc() {
  eNpcType arg1 ;
  Npc *result ;
  
  {
    AS3_GetScalarFromVar(arg1, _type);
  }
  result = (Npc *)new Npc(arg1);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Npc_Reset(self):void")))
void _wrap_Npc_Reset() {
  Npc *arg1 = (Npc *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  (arg1)->Reset();
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Npc_SetPlayer(self, player:int):void")))
void _wrap_Npc_SetPlayer() {
  Npc *arg1 = (Npc *) 0 ;
  Player *arg2 = (Player *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, player);
  }
  (arg1)->SetPlayer(arg2);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Npc_Update(self, deltaTime:Number):void")))
void _wrap_Npc_Update() {
  Npc *arg1 = (Npc *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, deltaTime);
  }
  (arg1)->Update(arg2);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Npc_setClockwise(self):void")))
void _wrap_Npc_setClockwise() {
  Npc *arg1 = (Npc *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  (arg1)->setClockwise();
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Npc_setClockwiseAs(self, isClockwise:Boolean):void")))
void _wrap_Npc_setClockwiseAs() {
  Npc *arg1 = (Npc *) 0 ;
  bool arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, isClockwise);
  }
  (arg1)->setClockwiseAs(arg2);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Npc_getPosX(self):Number")))
void _wrap_Npc_getPosX() {
  Npc *arg1 = (Npc *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float)(arg1)->getPosX();
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Npc_getPosY(self):Number")))
void _wrap_Npc_getPosY() {
  Npc *arg1 = (Npc *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float)(arg1)->getPosY();
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Npc_getRadius(self):Number")))
void _wrap_Npc_getRadius() {
  Npc *arg1 = (Npc *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float)(arg1)->getRadius();
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Npc_getAlive(self):Boolean")))
void _wrap_Npc_getAlive() {
  Npc *arg1 = (Npc *) 0 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (bool)(arg1)->getAlive();
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Npc_fire(self):void")))
void _wrap_Npc_fire() {
  Npc *arg1 = (Npc *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  (arg1)->fire();
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Npc_getbFired(self):Boolean")))
void _wrap_Npc_getbFired() {
  Npc *arg1 = (Npc *) 0 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (bool)(arg1)->getbFired();
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_Npc_setbFired(self, f:Boolean):Boolean")))
void _wrap_Npc_setbFired() {
  Npc *arg1 = (Npc *) 0 ;
  bool arg2 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, f);
  }
  result = (bool)(arg1)->setbFired(arg2);
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_delete_Npc(self):void")))
void _wrap_delete_Npc() {
  Npc *arg1 = (Npc *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  delete arg1;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_SceneData_width_set(self, width:Number):void")))
void _wrap_SceneData_width_set() {
  SceneData *arg1 = (SceneData *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, width);
  }
  if (arg1) (arg1)->width = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_SceneData_width_get(self):Number")))
void _wrap_SceneData_width_get() {
  SceneData *arg1 = (SceneData *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float) ((arg1)->width);
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_SceneData_height_set(self, height:Number):void")))
void _wrap_SceneData_height_set() {
  SceneData *arg1 = (SceneData *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, height);
  }
  if (arg1) (arg1)->height = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_SceneData_height_get(self):Number")))
void _wrap_SceneData_height_get() {
  SceneData *arg1 = (SceneData *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float) ((arg1)->height);
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_new_SceneData():int")))
void _wrap_new_SceneData() {
  SceneData *result ;
  
  result = (SceneData *)new SceneData();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_delete_SceneData(self):void")))
void _wrap_delete_SceneData() {
  SceneData *arg1 = (SceneData *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  delete arg1;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_PlayerData_posX_set(self, posX:Number):void")))
void _wrap_PlayerData_posX_set() {
  PlayerData *arg1 = (PlayerData *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, posX);
  }
  if (arg1) (arg1)->posX = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_PlayerData_posX_get(self):Number")))
void _wrap_PlayerData_posX_get() {
  PlayerData *arg1 = (PlayerData *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float) ((arg1)->posX);
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_PlayerData_posY_set(self, posY:Number):void")))
void _wrap_PlayerData_posY_set() {
  PlayerData *arg1 = (PlayerData *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, posY);
  }
  if (arg1) (arg1)->posY = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_PlayerData_posY_get(self):Number")))
void _wrap_PlayerData_posY_get() {
  PlayerData *arg1 = (PlayerData *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float) ((arg1)->posY);
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_PlayerData_isAlive_set(self, isAlive:Boolean):void")))
void _wrap_PlayerData_isAlive_set() {
  PlayerData *arg1 = (PlayerData *) 0 ;
  bool arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, isAlive);
  }
  if (arg1) (arg1)->isAlive = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_PlayerData_isAlive_get(self):Boolean")))
void _wrap_PlayerData_isAlive_get() {
  PlayerData *arg1 = (PlayerData *) 0 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (bool) ((arg1)->isAlive);
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_new_PlayerData():int")))
void _wrap_new_PlayerData() {
  PlayerData *result ;
  
  result = (PlayerData *)new PlayerData();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_delete_PlayerData(self):void")))
void _wrap_delete_PlayerData() {
  PlayerData *arg1 = (PlayerData *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  delete arg1;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_NpcData_posX_set(self, posX:Number):void")))
void _wrap_NpcData_posX_set() {
  NpcData *arg1 = (NpcData *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, posX);
  }
  if (arg1) (arg1)->posX = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_NpcData_posX_get(self):Number")))
void _wrap_NpcData_posX_get() {
  NpcData *arg1 = (NpcData *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float) ((arg1)->posX);
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_NpcData_posY_set(self, posY:Number):void")))
void _wrap_NpcData_posY_set() {
  NpcData *arg1 = (NpcData *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, posY);
  }
  if (arg1) (arg1)->posY = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_NpcData_posY_get(self):Number")))
void _wrap_NpcData_posY_get() {
  NpcData *arg1 = (NpcData *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float) ((arg1)->posY);
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_NpcData_bFired_set(self, bFired:Boolean):void")))
void _wrap_NpcData_bFired_set() {
  NpcData *arg1 = (NpcData *) 0 ;
  bool arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, bFired);
  }
  if (arg1) (arg1)->bFired = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_NpcData_bFired_get(self):Boolean")))
void _wrap_NpcData_bFired_get() {
  NpcData *arg1 = (NpcData *) 0 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (bool) ((arg1)->bFired);
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_NpcData_isAlive_set(self, isAlive:Boolean):void")))
void _wrap_NpcData_isAlive_set() {
  NpcData *arg1 = (NpcData *) 0 ;
  bool arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, isAlive);
  }
  if (arg1) (arg1)->isAlive = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_NpcData_isAlive_get(self):Boolean")))
void _wrap_NpcData_isAlive_get() {
  NpcData *arg1 = (NpcData *) 0 ;
  bool result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (bool) ((arg1)->isAlive);
  {
    AS3_DeclareVar(asresult, Boolean);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_NpcData_npcDataSize_set(self, npcDataSize:int):void")))
void _wrap_NpcData_npcDataSize_set() {
  NpcData *arg1 = (NpcData *) 0 ;
  int arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, npcDataSize);
  }
  if (arg1) (arg1)->npcDataSize = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_NpcData_npcDataSize_get(self):int")))
void _wrap_NpcData_npcDataSize_get() {
  NpcData *arg1 = (NpcData *) 0 ;
  int result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (int) ((arg1)->npcDataSize);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_new_NpcData():int")))
void _wrap_new_NpcData() {
  NpcData *result ;
  
  result = (NpcData *)new NpcData();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_delete_NpcData(self):void")))
void _wrap_delete_NpcData() {
  NpcData *arg1 = (NpcData *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  delete arg1;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletData_posX_set(self, posX:Number):void")))
void _wrap_BulletData_posX_set() {
  BulletData *arg1 = (BulletData *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, posX);
  }
  if (arg1) (arg1)->posX = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletData_posX_get(self):Number")))
void _wrap_BulletData_posX_get() {
  BulletData *arg1 = (BulletData *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float) ((arg1)->posX);
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletData_posY_set(self, posY:Number):void")))
void _wrap_BulletData_posY_set() {
  BulletData *arg1 = (BulletData *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, posY);
  }
  if (arg1) (arg1)->posY = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletData_posY_get(self):Number")))
void _wrap_BulletData_posY_get() {
  BulletData *arg1 = (BulletData *) 0 ;
  float result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (float) ((arg1)->posY);
  {
    AS3_DeclareVar(asresult, Number);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletData_bulletDataSize_set(self, bulletDataSize:int):void")))
void _wrap_BulletData_bulletDataSize_set() {
  BulletData *arg1 = (BulletData *) 0 ;
  int arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, bulletDataSize);
  }
  if (arg1) (arg1)->bulletDataSize = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BulletData_bulletDataSize_get(self):int")))
void _wrap_BulletData_bulletDataSize_get() {
  BulletData *arg1 = (BulletData *) 0 ;
  int result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (int) ((arg1)->bulletDataSize);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_new_BulletData():int")))
void _wrap_new_BulletData() {
  BulletData *result ;
  
  result = (BulletData *)new BulletData();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_delete_BulletData(self):void")))
void _wrap_delete_BulletData() {
  BulletData *arg1 = (BulletData *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  delete arg1;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGameData_sceneData_set(self, sceneData:int):void")))
void _wrap_ODGameData_sceneData_set() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  SceneData *arg2 = (SceneData *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, sceneData);
  }
  if (arg1) (arg1)->sceneData = *arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGameData_sceneData_get(self):int")))
void _wrap_ODGameData_sceneData_get() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  SceneData *result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (SceneData *)& ((arg1)->sceneData);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGameData_score_set(self, score:int):void")))
void _wrap_ODGameData_score_set() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  int arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, score);
  }
  if (arg1) (arg1)->score = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGameData_score_get(self):int")))
void _wrap_ODGameData_score_get() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  int result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (int) ((arg1)->score);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGameData_playerData_set(self, playerData:int):void")))
void _wrap_ODGameData_playerData_set() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  PlayerData *arg2 = (PlayerData *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, playerData);
  }
  if (arg1) (arg1)->playerData = *arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGameData_playerData_get(self):int")))
void _wrap_ODGameData_playerData_get() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  PlayerData *result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (PlayerData *)& ((arg1)->playerData);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGameData_bulletsData_set(self, bulletsData:int):void")))
void _wrap_ODGameData_bulletsData_set() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  BulletData *arg2 = (BulletData *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, bulletsData);
  }
  if (arg1) (arg1)->bulletsData = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGameData_bulletsData_get(self):int")))
void _wrap_ODGameData_bulletsData_get() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  BulletData *result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (BulletData *) ((arg1)->bulletsData);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGameData_bulletsNumber_set(self, bulletsNumber:int):void")))
void _wrap_ODGameData_bulletsNumber_set() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  int arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, bulletsNumber);
  }
  if (arg1) (arg1)->bulletsNumber = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGameData_bulletsNumber_get(self):int")))
void _wrap_ODGameData_bulletsNumber_get() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  int result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (int) ((arg1)->bulletsNumber);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGameData_npcData_set(self, npcData:int):void")))
void _wrap_ODGameData_npcData_set() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  NpcData *arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, npcData);
  }
  {
    size_t ii;
    NpcData *b = (NpcData *) arg1->npcData;
    for (ii = 0; ii < (size_t)ENpcTypeMax; ii++) b[ii] = *((NpcData *) arg2 + ii);
  }
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGameData_npcData_get(self):int")))
void _wrap_ODGameData_npcData_get() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  NpcData *result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (NpcData *)(NpcData *) ((arg1)->npcData);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_new_ODGameData():int")))
void _wrap_new_ODGameData() {
  ODGameData *result ;
  
  result = (ODGameData *)new ODGameData();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_delete_ODGameData(self):void")))
void _wrap_delete_ODGameData() {
  ODGameData *arg1 = (ODGameData *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  delete arg1;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_new_ODGame():int")))
void _wrap_new_ODGame() {
  ODGame *result ;
  
  result = (ODGame *)new ODGame();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGame_Reset(self):void")))
void _wrap_ODGame_Reset() {
  ODGame *arg1 = (ODGame *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  (arg1)->Reset();
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGame_getODGameData(self):int")))
void _wrap_ODGame_getODGameData() {
  ODGame *arg1 = (ODGame *) 0 ;
  ODGameData *result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (ODGameData *)(arg1)->getODGameData();
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGame_UpdateCommand(self, commandID:int, bcommandOn:Boolean):void")))
void _wrap_ODGame_UpdateCommand() {
  ODGame *arg1 = (ODGame *) 0 ;
  int arg2 ;
  bool arg3 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, commandID);
  }
  {
    AS3_GetScalarFromVar(arg3, bcommandOn);
  }
  (arg1)->UpdateCommand(arg2,arg3);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGame_Update(self, delta:Number):void")))
void _wrap_ODGame_Update() {
  ODGame *arg1 = (ODGame *) 0 ;
  float arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, delta);
  }
  (arg1)->Update(arg2);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_ODGame_UpdateData(self):void")))
void _wrap_ODGame_UpdateData() {
  ODGame *arg1 = (ODGame *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  (arg1)->UpdateData();
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_delete_ODGame(self):void")))
void _wrap_delete_ODGame() {
  ODGame *arg1 = (ODGame *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  delete arg1;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


